#!/usr/bin/env bash

# Usage:
# git check-all-downstream-status
#   See changes if any. Resolve them in a different terminal and choose y/n.
#
# git check-all-downstream-status --restore-vendor-changes
#   Automatically remove unintended/unnecessary vendor changes.

current_branch=$(git rev-parse --abbrev-ref HEAD)
restore_vendor_changes=false
if [[ "$*" == *"restore-vendor-changes"* ]]; then
  restore_vendor_changes=true
  VENDOR_DIR="src/go/src/rubrik/vendor"
fi

while true; do
  git checkout "$current_branch"
  
  while true; do
    git_diff=$(git diff --stat)

    if [[ -n $git_diff ]]; then
      # Perform actions when there are changes
      echo "There are changes."
      git status
      if $restore_vendor_changes; then
        echo "Restoring changes to vendor"
        git restore $VENDOR_DIR
      else
        echo "After resolving the changes, please press 'y' to re-run this iteration or 'n' to exit: "
        read -r choice

        if [[ $choice == "y" ]]; then
          # Add your desired commands or actions to continue
          echo "Re-running the current iteration..."
        elif [[ $choice == "n" ]]; then
          # Add your desired commands or actions to exit
          echo "Exiting..."
          exit 0
        else
          echo "Invalid input. Please try again."
        fi
      fi 
    else
      # Perform actions when there are no changes
      echo "No changes found."
      break  # Break out of the nested loop
    fi
  done

  # Other desired actions for the current iteration here

  downstream=$(git first-downstream)
  if [[ $downstream == "null" ]]; then
    # Exit when there are no more downstream branches
    echo "No more downstream branches."
    exit 0
  fi

  current_branch=$downstream
done
